quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL_POSTGRE}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME_POSTGRE}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD_POSTGRE}

quarkus.mongodb.database = packovery
quarkus.mongodb.connection-string=${QUARKUS_DATASOURCE_URL_MONGODB}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.scripts.generation.target=no-file

quarkus.mailer.from=Packovery <noreply@packovery.com>
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${MAIL_USERNAME}
quarkus.mailer.password=${MAIL_PASSWORD}
quarkus.mailer.mock=false


mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=packovery
